import { FrameConfig } from './types';

export interface FramePreset {
  name: string;
  type: FrameConfig['type'];
  description: string;
  config: Partial<FrameConfig>;
}

export const framePresets: FramePreset[] = [
  { name: 'None', type: 'none', description: 'No frame', config: { type: 'none' } },
  {
    name: 'Simple',
    type: 'simple',
    description: 'Clean product card',
    config: {
      type: 'simple',
      badgeText: 'Quick Access',
      bgColor: '#FFFFFF',
      borderColor: '#D7DCE5',
      textColor: '#111827',
      accentColor: '#4F46E5',
      badgeColor: '#EEF2FF',
      badgeTextColor: '#4338CA',
      qrBackgroundColor: '#F8FAFC',
      padding: 22,
      fontSize: 16,
      borderWidth: 2,
      cornerRadius: 24,
      shadow: 14,
    },
  },
  {
    name: 'Rounded',
    type: 'rounded',
    description: 'Soft branded card',
    config: {
      type: 'rounded',
      badgeText: 'Scan & Explore',
      bgColor: '#FFFFFF',
      borderColor: '#C7D2FE',
      textColor: '#1E1B4B',
      accentColor: '#6366F1',
      badgeColor: '#6366F1',
      badgeTextColor: '#FFFFFF',
      qrBackgroundColor: '#EEF2FF',
      padding: 24,
      fontSize: 17,
      borderWidth: 2,
      cornerRadius: 30,
      shadow: 22,
    },
  },
  {
    name: 'Bold',
    type: 'bold',
    description: 'Campaign-ready impact',
    config: {
      type: 'bold',
      badgeText: 'Limited Offer',
      bgColor: '#FFF1C7',
      borderColor: '#111827',
      textColor: '#111827',
      accentColor: '#F97316',
      badgeColor: '#111827',
      badgeTextColor: '#FFFFFF',
      qrBackgroundColor: '#FFFFFF',
      padding: 28,
      fontSize: 20,
      borderWidth: 4,
      cornerRadius: 26,
      shadow: 20,
    },
  },
  {
    name: 'Minimal',
    type: 'minimal',
    description: 'Elegant and understated',
    config: {
      type: 'minimal',
      badgeText: '',
      bgColor: '#FFFFFF',
      borderColor: '#E5E7EB',
      textColor: '#374151',
      accentColor: '#9CA3AF',
      badgeColor: '#F3F4F6',
      badgeTextColor: '#4B5563',
      qrBackgroundColor: '#FFFFFF',
      padding: 18,
      fontSize: 15,
      borderWidth: 1,
      cornerRadius: 20,
      shadow: 8,
    },
  },
  {
    name: 'Social',
    type: 'social',
    description: 'Creator and social CTA',
    config: {
      type: 'social',
      badgeText: 'Follow Us',
      bgColor: '#F8FBFF',
      borderColor: '#93C5FD',
      textColor: '#0F172A',
      accentColor: '#0EA5E9',
      badgeColor: '#0EA5E9',
      badgeTextColor: '#FFFFFF',
      qrBackgroundColor: '#FFFFFF',
      padding: 24,
      fontSize: 17,
      borderWidth: 2,
      cornerRadius: 28,
      shadow: 18,
    },
  },
  {
    name: 'Premium',
    type: 'premium',
    description: 'Luxury dark presentation',
    config: {
      type: 'premium',
      badgeText: 'VIP Access',
      bgColor: '#101827',
      borderColor: '#C8A55A',
      textColor: '#F8E7BF',
      accentColor: '#C8A55A',
      badgeColor: '#C8A55A',
      badgeTextColor: '#101827',
      qrBackgroundColor: '#182132',
      padding: 28,
      fontSize: 18,
      borderWidth: 3,
      cornerRadius: 30,
      shadow: 26,
    },
  },
  {
    name: 'Glass',
    type: 'glass',
    description: 'Soft layered glass card',
    config: {
      type: 'glass',
      badgeText: 'Smart Link',
      bgColor: '#F6FAFF',
      borderColor: '#D6E4FF',
      textColor: '#0F172A',
      accentColor: '#38BDF8',
      badgeColor: '#E0F2FE',
      badgeTextColor: '#0369A1',
      qrBackgroundColor: '#FFFFFF',
      padding: 24,
      fontSize: 16,
      borderWidth: 1,
      cornerRadius: 32,
      shadow: 24,
    },
  },
  {
    name: 'Spotlight',
    type: 'spotlight',
    description: 'Dark contrast hero card',
    config: {
      type: 'spotlight',
      badgeText: 'Tap to Open',
      bgColor: '#0F172A',
      borderColor: '#334155',
      textColor: '#F8FAFC',
      accentColor: '#22C55E',
      badgeColor: '#22C55E',
      badgeTextColor: '#052E16',
      qrBackgroundColor: '#FFFFFF',
      padding: 26,
      fontSize: 17,
      borderWidth: 2,
      cornerRadius: 28,
      shadow: 28,
    },
  },
];

export const frameSuggestions = [
  'Scan Me', 'Open Website', 'View Menu', 'Follow Us', 'Connect to WiFi',
  'Download App', 'Learn More', 'Get Offer', 'Join Us', 'Visit Us',
];

export const frameTopSuggestions = [
  'Instant Access',
  'Exclusive Link',
  'Official QR',
  'Scan to Continue',
  'Smart Shortcut',
  'Fast Entry',
];

export const frameBadgeSuggestions = [
  'New',
  'Featured',
  'Quick Access',
  'Special Offer',
  'VIP Access',
  'Official',
];
